### ISSUE TITLE
More linters?

### ISSUE THREAD

**Issue by fjsj** [vintasoftware/django-react-boilerplate#22]
https://www.pylint.org/
https://pypi.python.org/pypi/radon
https://anonscm.debian.org/cgit/collab-maint/check-all-the-things.git/tree/data/python
https://github.com/PyCQA/

**Comment by fjsj** [comment]
https://github.com/PyCQA/pep8-naming

**Comment by fjsj** [comment]
http://prospector.landscape.io/

sample config:
```
output-format: text

strictness: veryhigh
test-warnings: true
doc-warnings: false
member-warnings: true

uses:
  - django
  - celery

pep8:
  options:
    max-line-length: 100

vulture:
  run: true

ignore-paths:
  - node_modules
  - venv
  - env
  - cacheback

ignore-patterns:
  - (^|/)migrations(/|$)
  - (^|/)settings(/|$)

```

**Comment by chocoelho** [comment]
I think that Prospector can be a good choice, I came up with the following `.prospector.yaml`:

```
output-format: text

strictness: veryhigh
test-warnings: true
doc-warnings: false
member-warnings: true

uses:
  - django
  - celery

pep8:
  full: true
  disable:
    - D100
    - D101
    - D102
    - D103
    - D105
    - D205
    - D400 
  options:
    max-line-length: 100

pylint:
  options:
    max-line-length: 100

vulture:
  run: true

ignore-paths:
  - node_modules
  - venv
  - env

ignore-patterns:
  - (^|/)migrations(/|$)
  - (^|/)settings(/|$)
```

What do you think about it @fjsj?

**Comment by chocoelho** [comment]
Just a note: the additions I made were based on our current `.flake8` config file, this was applied to `pep8` section and `pylint` as well.

**Comment by fjsj** [comment]
looks great to me!
might be good to test in our clients projects to check if we need to ignore more false-positive errors @chocoelho

**Comment by chocoelho** [comment]
I added to a project I'm working on using Python 3.6.1 and faced some issues with prospector. It's described here at landscapeio/prospector#200. I'm not sure it's safe to migrate to prospector while this is not fixed. What are your thoughts on this @fjsj?

**Comment by chocoelho** [comment]
Also, it's throws `AttributeError: 'FlakesChecker' object has no attribute 'ANNASSIGN'` when running pre-commit, thus we'll need to wait for the fix to consider using `prospector`.

**Comment by chocoelho** [comment]
@fjsj what do you think of disabling `E701` checkage? This is related to `multiple statements on one line (colon)`...

**Comment by chocoelho** [comment]
Also, taking a lookt at thorgate/django-projectemplate [.prospector.yaml](https://github.com/thorgate/django-project-template/blob/docker/%7B%7Bcookiecutter.repo_name%7D%7D/%7B%7Bcookiecutter.repo_name%7D%7D/.prospector.yaml#L18), they disable unused argument checkage. Do you think we add this to our `.prospector.yaml` as well?

**Comment by chocoelho** [comment]
As a reference, I managed to evolve `.prospector.yaml` to this:

```
output-format: text

strictness: veryhigh
test-warnings: true
doc-warnings: false
member-warnings: true

uses:
  - django
  - celery

pep8:
  full: true
  disable:
    - D100
    - D101
    - D102
    - D103
    - D105
    - D205
    - D400 
    - E701
  options:
    max-line-length: 100

pylint:
  disable:
    - unused-argument
  options:
    max-line-length: 100

pyflakes:
  disable:
    - F401

vulture:
  disable:
    - unused-function
  run: true

ignore-paths:
  - node_modules
  - venv
  - env

ignore-patterns:
  - (^|/)migrations(/|$)
  - (^|/)settings(/|$)
```
