### ISSUE TITLE
python manage.py makemigrations gave me  ttributeError: module 'django.views.debug' has no attribute 'TECHNICAL_500_TEMPLATE' error

### ISSUE THREAD

**Issue by whitehawk0011** [vintasoftware/django-react-boilerplate#166]
Steps I took..

 Started the project by this command
`django-admin startproject theprojectname --extension py,yml,json --name Procfile,README.md,.env.example --template=https://github.com/vintasoftware/django-react-boilerplate/archive/boilerplate-release.zip`

then i installed the pip packages
 
 

`pip install -r requirements-to-freeze.txt`
Saved them 

 `pip freeze > requirements.txt`

Ran the npm update commands
```
 npm update --save
 npm update --save-dev

```

```
cp goDiary/settings/local.py.example goDiary/settings/local.py
cp .env.example .env
```
and after that 

> `python manage.py makemigrations`

This was the output

```
(myvenv2) shubhendu@shubhendu-HP-Pavilion-g6-Notebook-PC:/home/goDiary$ python manage.py makemigrations
Traceback (most recent call last):
  File "manage.py", line 27, in <module>
    execute_from_command_line(sys.argv)
  File "/home/goDiary/myvenv2/lib/python3.5/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/home/goDiary/myvenv2/lib/python3.5/site-packages/django/core/management/__init__.py", line 347, in execute
    django.setup()
  File "/home/goDiary/myvenv2/lib/python3.5/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/goDiary/myvenv2/lib/python3.5/site-packages/django/apps/registry.py", line 89, in populate
    app_config = AppConfig.create(entry)
  File "/home/goDiary/myvenv2/lib/python3.5/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/goDiary/myvenv2/lib/python3.5/site-packages/fixmydjango/__init__.py", line 22, in <module>
    original_TECHNICAL_500_TEMPLATE = debug.TECHNICAL_500_TEMPLATE
AttributeError: module 'django.views.debug' has no attribute 'TECHNICAL_500_TEMPLATE'

```

**Comment by lucabezerra** [comment]
This seems to be an issue with `fixmydjango`. For now, I think you can just comment out these 2 lines on `goDiary/settings/local_base.py`:

```
INSTALLED_APPS += ('fixmydjango',)
FIX_MY_DJANGO_ADMIN_MODE = True
```
(lines 58 & 59 here)

@filipeximenes Do you confirm this, or am I talking nonsense? Haha :)

**Comment by whitehawk0011** [comment]
Thanks for responding

Ya I actually am running 2.0.0 django.
 , I have done as you said, 
```

(myvenv2) shubhendu@shubhendu-HP-Pavilion-g6-Notebook-PC:/home/goDiary$ python manage.py makemigrations
Traceback (most recent call last):
  File "/home/goDiary/myvenv2/lib/python3.5/site-packages/django/apps/registry.py", line 147, in get_app_config
    return self.app_configs[app_label]
KeyError: 'users'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/goDiary/myvenv2/lib/python3.5/site-packages/django/contrib/auth/__init__.py", line 193, in get_user_model
    return django_apps.get_model(settings.AUTH_USER_MODEL, require_ready=False)
  File "/home/goDiary/myvenv2/lib/python3.5/site-packages/django/apps/registry.py", line 197, in get_model
    app_config = self.get_app_config(app_label)
  File "/home/goDiary/myvenv2/lib/python3.5/site-packages/django/apps/registry.py", line 154, in get_app_config
    raise LookupError(message)
LookupError: No installed app with label 'users'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 27, in <module>
    execute_from_command_line(sys.argv)
  File "/home/goDiary/myvenv2/lib/python3.5/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/home/goDiary/myvenv2/lib/python3.5/site-packages/django/core/management/__init__.py", line 347, in execute
    django.setup()
  File "/home/goDiary/myvenv2/lib/python3.5/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/goDiary/myvenv2/lib/python3.5/site-packages/django/apps/registry.py", line 120, in populate
    app_config.ready()
  File "/home/goDiary/myvenv2/lib/python3.5/site-packages/django/contrib/admin/apps.py", line 23, in ready
    self.module.autodiscover()
  File "/home/goDiary/myvenv2/lib/python3.5/site-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/home/goDiary/myvenv2/lib/python3.5/site-packages/django/utils/module_loading.py", line 47, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/goDiary/myvenv2/lib/python3.5/site-packages/django/contrib/auth/admin.py", line 6, in <module>
    from django.contrib.auth.forms import (
  File "/home/goDiary/myvenv2/lib/python3.5/site-packages/django/contrib/auth/forms.py", line 20, in <module>
    UserModel = get_user_model()
  File "/home/goDiary/myvenv2/lib/python3.5/site-packages/django/contrib/auth/__init__.py", line 198, in get_user_model
    "AUTH_USER_MODEL refers to model '%s' that has not been installed" % settings.AUTH_USER_MODEL
django.core.exceptions.ImproperlyConfigured: AUTH_USER_MODEL refers to model 'users.User' that has not been installed

```
My Team Leader wanted us to keep it strictly Django 2 and python 3.5, which I think is causing problem
I think I need to either resort to Django 1.11 or proceed with 2.0 I wanted to use this since it is good maintained project and it has all I needed for the new project 

I hope you can provide some source where I can get better help. Thank you very much

**Comment by whitehawk0011** [comment]
Ya I am sorry but I was using Django 2.0 as the client had demanded 
I tried your way.

```

(myvenv2) shubhendu@shubhendu-HP-Pavilion-g6-Notebook-PC:/home/goDiary$ python manage.py makemigrations
Traceback (most recent call last):
  File "manage.py", line 27, in <module>
    execute_from_command_line(sys.argv)
  File "/home/goDiary/myvenv2/lib/python3.5/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/home/goDiary/myvenv2/lib/python3.5/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/goDiary/myvenv2/lib/python3.5/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/goDiary/myvenv2/lib/python3.5/site-packages/django/core/management/base.py", line 332, in execute
    self.check()
  File "/home/goDiary/myvenv2/lib/python3.5/site-packages/django/core/management/base.py", line 364, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/goDiary/myvenv2/lib/python3.5/site-packages/django/core/management/base.py", line 351, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/goDiary/myvenv2/lib/python3.5/site-packages/django/core/checks/registry.py", line 73, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/goDiary/myvenv2/lib/python3.5/site-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "/home/goDiary/myvenv2/lib/python3.5/site-packages/django/core/checks/urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "/home/goDiary/myvenv2/lib/python3.5/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/goDiary/myvenv2/lib/python3.5/site-packages/django/urls/resolvers.py", line 536, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/goDiary/myvenv2/lib/python3.5/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/goDiary/myvenv2/lib/python3.5/site-packages/django/urls/resolvers.py", line 529, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/goDiary/goDiary/urls.py", line 5, in <module>
    import django_js_reverse.views
  File "/home/goDiary/myvenv2/lib/python3.5/site-packages/django_js_reverse/views.py", line 2, in <module>
    from django.core import urlresolvers
ImportError: cannot import name 'urlresolvers'
```

I will try this some more, otherwise will resort to django 1.11

If not, I dont know if I can find as good maintained project like this.
I needed this because it is very well done

**Comment by whitehawk0011** [comment]
Anyways your code is working fine on 1.11 , its ok if you close this issue thanks for the help.

**Comment by lucabezerra** [comment]
Yeah, it might be complicated to work around every issue that comes from using Django 2.0, it was a pretty major change. But I'm glad that it at least solved your question. Please let us know if you encounter any other issues and thanks for using it :)
